module.exports = Object.freeze({
  // IN CART
  STALE: 'STALE',

  // CHECKOUT PROCESS COMPLETED
  INITIATED: 'INITIATED',

  // BREAKPOINT, IF LENDER DECLINES
  DECLINED: 'DECLINED',

  // ORDER PLACED, IF LENDER ACCEPTS
  ACCEPTED: 'ACCEPTED',

  // LENDER -> WAREHOUSE -> CHECKS -> PACKAGING -> RENTER
  DROP: 'DROP',

  // ON RENT
  ONRENT: 'ONRENT',

  // RENTER -> WAREHOUSE -> CHECKS -> LENDER
  PICKUP: 'PICKUP',

  // DELIVERED TO LENDER, PAYMENT COMPLETED
  COMPLETED: 'COMPLETED',

  // EXTRAS

  // EXTENSION REQUESTED
  EXTENDED: 'EXTENDED',

  // ORDER CANCELLED BEFORE COMPLETION
  CANCELLED: 'CANCELLED',

  // REFUNDED MONEY, IF BREAKPOINT BEFORE COMPLETION (CANCELLATION & LENDER DECLINES)
  REFUNDED: 'REFUNDED'
});
