module.exports = Object.freeze({
  RADIO: "RADIO",
  SELECT: "SELECT",
  MSELECT: "MSELECT",
  TEXTBOX: "TEXTBOX",
  TEXTAREA: "TEXTAREA",
  SLIDER: "SLIDER",
  CHECKBOX: "CHECKBOX",
  COUNTRIES: "COUNTRIES",
});
