version: "3"
services:
  node:
    build:
      context: .
      args:
        APP_DIR: ${APP_DIR}
    environment:
      - NODE_ENV=production
    container_name: nodejs-starter-kit
    tty: true
    stdin_open: true
    volumes:
      - ./:${APP_DIR}:cached
      - ${APP_DIR}/build
      - ${APP_DIR}/node_modules
      - /home/node/.cache/yarn
    working_dir: ${APP_DIR}
    # user: node
    command: >
      sh -c '
      NODE_ENV=development yarn &&
      (test -f prod-db.sqlite3 || yarn seed) &&
      yarn build &&
      yarn start
      '
    ports:
      - 8080:8080
